table Dates
	lineageTag: 3414936e-ba7f-499d-9b1f-a1461e11ed4a

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1178f2e3-c01e-4574-a1b0-d60fec9d6c20
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 7dcf7191-0118-4aaa-b3c9-3dfc484ecf44
			defaultHierarchy: LocalDateTable_f0541822-94f6-42f7-b619-e7498bac87db.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Day Name'
		dataType: string
		lineageTag: 00170e61-8421-4a19-8db4-54fa10b9be1b
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 88fd5a56-523a-47d3-8304-4a5701190104
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column Week
		dataType: int64
		formatString: 0
		lineageTag: e3aa6a63-135a-4b58-bca1-f3759b5a9754
		summarizeBy: sum
		sourceColumn: Week

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 438065b5-8e65-44c6-b465-72dfefff03cc
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: aa8028fb-c561-44af-98dc-ecea128f8801
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: fc1b7e81-03df-4f0f-a7b8-e2139939098a
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	partition Dates = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Abhishek Raj\Downloads\QUESTION_Transformation3POWERBI.xlsx"), null, true),
				    Dates_Sheet = Source{[Item="Dates",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Dates_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", Int64.Type}, {"Day Name", type text}, {"Day", Int64.Type}, {"Week", Int64.Type}, {"Month", Int64.Type}, {"Quarter", Int64.Type}, {"Year", Int64.Type}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type any}, {"Column23", type any}, {"Column24", type any}, {"Column25", type any}, {"Column26", type any}, {"Column27", type any}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"Date", type date}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type1", {"Date", "Day Name", "Day", "Week", "Month", "Quarter", "Year"}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Errors", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Removed Blank Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

